# Camunda 8 connection
zeebe.client.broker.grpcAddress=http://localhost:26500
zeebe.client.security.plaintext=true

# App name
spring.application.name=loan-approval

# Disable security for now
zeebe.client.security.enabled=false

server.port = 8081